# Generated by Django 2.2.5 on 2019-10-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_updated_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
