# Generated by Django 2.2.6 on 2019-10-14 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas16pf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('points', models.IntegerField()),
                ('complete', models.BooleanField()),
                ('Preguntas16pf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Preguntas16pf')),
            ],
        ),
    ]
