# Generated by Django 2.2.6 on 2019-10-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Preguntas16pf',
        ),
        migrations.AddField(
            model_name='question',
            name='factor',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Preguntas16pf',
        ),
    ]
