# Generated by Django 2.2.6 on 2019-10-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20191016_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEvaluado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField()),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=300)),
                ('cedula', models.IntegerField()),
            ],
        ),
    ]
